### ISSUE TITLE
Some symbols are not accepted by the editor

### ISSUE THREAD

**Issue by Aparna-Dasgupta** [eduladder/texteditor#3]
I was trying to add a question which is given below.
https://eduladder.com/viewquestions/5180/Let-G-be-a-group-with-15-elements-Let-L-be-a-subgroup-of-G-It-is-known-that-L-not-equal-to-G-and-that-the-size-of-L-is-at-least-4-The-size-of-L-is----Gate-Computer-Science-2014
I was suppose to write "L≠G" but the "not equal to" symbol was not accepted by the editor. Hence I had to edit the question type "not equal to" in the question

**Comment by arunwebber** [comment]
https://github.com/eduladder/texteditor/issues/6
